### ISSUE TITLE
Running the cli in Windows results in a crash

### ISSUE THREAD

**Issue by LoganTann** [Embraser01/typoas#34]
I ran the following command : `npx @typoas/cli generate -i http://localhost:3232/api-json -o dist/client/client.ts`

Then, the bin.js script is executed in the windows script host interpreter instead of NodeJS

![image](https://github.com/Embraser01/typoas/assets/28659185/41fbc476-7b85-4889-8f64-0d7dc3f8dae9)

**Comment by Embraser01** [comment]
Hi,

Seems like NPM doesn't like when JS files are at top level in the `bin` field in package.json 😢
In the mean time, Yarn or pnpm are both working as expected.

Will mark this as a bug and try for a fix

**Comment by Embraser01** [comment]
Thank you for your help. I released a new version with the fix. From my testing, it should work now except for the following case:
When running npx inside an existing project, it fails with:
```
> Run npx @typoas/cli generate -i https://petstore3.swagger.io/api/v3/openapi.json -o test.ts
'typoas-cli' is not recognized as an internal or external command,
operable program or batch file.
> Error: Process completed with exit code 1.
```

I'm also adding some E2E tests to be sure.

**Comment by Embraser01** [comment]
Seems that it only fail in the typoas repo on Windows (maybe related to https://github.com/npm/cli/issues/6276) , I'm gonna close this
