### ISSUE TITLE
AuthProviders type doesn't work (always never)

### ISSUE THREAD

**Issue by Embraser01** [Embraser01/typoas#44]

**Comment by jaens** [comment]
Ah, okay, just discovered this, it makes this package basically unusable for authenticated APIs. Unfortunate.

**Comment by Embraser01** [comment]
Hi @jaens, this is only affecting TS typing, not the package behavior (should have made an example, almost forgot what was the issue).

The issue can easily be workaround by casting the return value of the `getConfig` function to `never`
![image](https://github.com/Embraser01/typoas/assets/8802277/dd5540ce-9160-4961-bbcf-bc2106df0c03)

**Comment by jaens** [comment]
Right, I guess that works, although it's highly... uhh... "unintuitive" :wink:

**Comment by Embraser01** [comment]
I agree this is not the best bug 😅Never took time to actually fix it. This should now be OK, just published `@typoas/runtime@3.1.2` containing the fix
