### ISSUE TITLE
incorrect TS generated when param name is like `page[number]`

### ISSUE THREAD

**Issue by WickyNilliams** [Embraser01/typoas#46]
when a param name (in this case query param) contains square brackets, it ends up generating types like this:

```ts
 {
    page[number]?: number;
    page[size]?: number;
    filter[search]?: string;
}
```

which is invalid TS. they need to be quoted. this style of query param is standard for [JSONAPI](https://jsonapi.org/)

**Comment by Embraser01** [comment]
Hey 👋 
I just released a new version of the cli and generator that fixes your issue (v3.1.5)
