### ISSUE TITLE
Internal Error: Unsupported security scheme 'openIdConnect'

### ISSUE THREAD

**Issue by leppaott** [Embraser01/typoas#69]
`Internal Error: Unsupported security scheme 'openIdConnect'`

https://swagger.io/docs/specification/authentication/openid-connect-discovery/
Apparently this isn't supported?

**Comment by Embraser01** [comment]
Hi,
The main issue with OpenIDConnect and OAuth2 is that it adds a lot of complexity if you want to support all the different flows to retrieve the accessToken.
For OAuth2, I added a simple support to use the retrieved accessToken and I guess it should be the same system for OpenIDConnect.

A workaround for now would be to change the security scheme type to OAuth2 which should work the same.
I'll add support for OIDC

**Comment by Embraser01** [comment]
This should now be resolved in the latest version (4.1.0)
